Warn user when choosing wrong wall viscosity model
trixi-framework/TrixiParticles.jl pull request #445
Opened 2024-03-06 10:46 UTC by LasNikas

Allow `ArtificialViscosityMonaghan` as wall viscosity model but print out warning. 
(Otherwise it prints weird cache errors when accidentally choosing the wrong viscosity model

As we can see, it would work...
![image](https://github.com/trixi-framework/TrixiParticles.jl/assets/73897120/ba603c7a-b3ca-4ecf-a7ea-53a2cc6b145a)

2024-03-06 10:50 UTC, efaulhaber commented on src/schemes/boundary/dummy_particles/dummy_particles.jl
> +
Do we want to have a warning here? I'd say it's enough to have a warning in the docs.

2024-03-06 22:24 UTC, svchb requested changes

2024-03-06 22:24 UTC, svchb commented on src/schemes/boundary/system.jl
> +@inline function viscous_velocity(v, ::Nothing, system, particle)
```suggestion
@inline function viscous_velocity(v, viscosity::Nothing, system, particle)
```

2024-03-07 10:28 UTC, svchb approved these changes

2024-03-20 12:12 UTC, merged