Revise custom quantities
trixi-framework/TrixiParticles.jl pull request #457
Opened 2024-03-10 19:58 UTC by efaulhaber

2024-03-11 08:55 UTC, svchb approved these changes

2024-03-11 10:00 UTC, LasNikas requested changes

2024-03-11 10:00 UTC, LasNikas commented on src/general/custom_quantities.jl
> +    # When the dummy particles model is used, i.e., boundary particles behave like fliud
```suggestion
    # When the dummy particles model is used, i.e., boundary particles behave like fluid
```

2024-03-12 17:18 UTC, LasNikas approved these changes

2024-03-12 17:33 UTC, merged