Example on how to save interpolated planes using postprocessing callback
trixi-framework/TrixiParticles.jl pull request #462
Opened 2024-03-13 13:54 UTC by svchb

2024-03-17 21:36 UTC, efaulhaber commented on src/general/interpolation.jl
> +    sol = (; u=[(; x=(v, u))])
#466 is the clean solution for this.

2024-03-17 21:36 UTC, efaulhaber commented on examples/fluid/dam_break_2d.jl
> +#                              semi, system, v, u, filename="plane_$file_id.vti")
This is not correct! These have to be the unwrapped `v_ode` and `u_ode`. I realized that I forgot to send my comment in #424 that we don't just need a version with `v` and `u`, but also `v_ode`, `u_ode` and `semi`.

2024-03-19 11:24 UTC, svchb commented
Lets merge #466 than first and I will fix this.

2024-05-31 07:56 UTC, efaulhaber requested changes
Why in the `dam_break_2d.jl` example and not in `examples/postprocessing/postprocessing.jl`? That seems to be the right place for this.

2024-05-31 07:56 UTC, efaulhaber commented on examples/fluid/dam_break_2d.jl
> +saving_callback = SolutionSavingCallback(dt=0.1, prefix=solution_prefix)
Why?

2024-05-31 07:56 UTC, efaulhaber commented on examples/fluid/dam_break_2d.jl
> +# Example on how interpolated planes can be saved using the postprocessing callback.
```suggestion
# Example on how interpolated planes can be saved using the postprocessing callback
```

2024-05-31 07:56 UTC, efaulhaber commented on examples/fluid/dam_break_2d.jl
> +    file_id = Int(ceil(t * 10000))
```suggestion
    file_id = ceil(Int, t * 10000)
```

2024-06-19 08:01 UTC, efaulhaber approved these changes

2024-06-19 08:44 UTC, merged