Add wrapper for internal use of interpolation functions
trixi-framework/TrixiParticles.jl pull request #466
Opened 2024-03-15 14:45 UTC by LasNikas

2024-03-15 14:47 UTC, svchb commented
Conflict with #462

2024-03-15 14:50 UTC, LasNikas commented
Ah didn't notice. But why should we create a named tuple which is then unpacked again in the method?

2024-03-15 14:53 UTC, svchb commented
Yes I wanted to mention that this conflicts. I also thought about this but I wanted to keep the changes minimal in #462.

2024-03-20 13:57 UTC, svchb approved these changes

2024-04-02 10:23 UTC, efaulhaber approved these changes

2024-04-02 10:23 UTC, efaulhaber commented on src/general/interpolation.jl
> +    u_ode = sol.u[end].x[2]
```suggestion
    v_ode, u_ode = sol.u[end].x
```

2024-04-02 10:27 UTC, efaulhaber requested changes

2024-04-02 10:27 UTC, efaulhaber commented on src/general/interpolation.jl
> +    u_ode = sol.u[end].x[2]
```suggestion
    v_ode, u_ode = sol.u[end].x
```

2024-04-03 10:50 UTC, svchb approved these changes

2024-04-03 13:09 UTC, svchb approved these changes

2024-04-03 13:10 UTC, merged