Support different systems in Interpolation
trixi-framework/TrixiParticles.jl pull request #505
Opened 2024-04-24 12:58 UTC by svchb

Fix #464

2024-07-22 10:04 UTC, efaulhaber requested changes

2024-07-22 10:04 UTC, efaulhaber commented on src/general/interpolation.jl
> +                                                                           for val in values(system_specific_return)))
```suggestion
        system_specific_return = map(system_specific_return) do val
           if val isa AbstractArray
               return fill(NaN, size(val))
           else
               return NaN
           end
       end
```

2024-07-22 10:04 UTC, efaulhaber commented on src/general/interpolation.jl
> +    interpolation_values = zeros(no_interpolation_values)
```suggestion
    interpolation_values = zeros(n_interpolation_values(ref_system))
```

2024-07-23 14:16 UTC, efaulhaber approved these changes

2024-07-23 15:31 UTC, LasNikas approved these changes

2024-07-23 15:34 UTC, merged