Remove `pinv` in correction matrix inversion step
trixi-framework/TrixiParticles.jl pull request #526
Opened 2024-05-15 08:09 UTC by efaulhaber

The `SMatrix` implementation of `pinv` is just falling back to the regular matrix definition, which is then causing allocations and is 400x slower than `inv` for an `SMatrix`.
We found that the matrix is singular if and only if a particle and all neighbors are collinear (in 2D) or lie on the same plane (in 3D). This only happens when either two (in 2D) or three (in 3D) particles are isolated, or on the edges of a very deformed domain. So only in edge cases where the fluid itself has a singularity.
In these cases, we now just disable the correction and use the uncorrected gradient instead. Also see the proof in the comments.

2024-05-15 09:57 UTC, svchb requested changes
Its fine just update the reference files.

2024-05-15 11:34 UTC, bennibolm approved these changes

2024-05-15 11:55 UTC, LasNikas submitted a review, later dismissed
Nice catch! Also, thanks for the proof. That makes sense

2024-05-16 16:30 UTC, LasNikas approved these changes

2024-05-17 16:01 UTC, svchb approved these changes

2024-05-17 16:01 UTC, merged