Add type `GPUSystem` to determine if a system is stored on the CPU or GPU
trixi-framework/TrixiParticles.jl pull request #532
Opened 2024-05-22 13:03 UTC by efaulhaber

I split #493 into multiple smaller parts. This here is the first part.

2024-05-24 12:26 UTC, LasNikas requested changes
LGTM! Only a few formatting issues

2024-05-24 12:26 UTC, LasNikas commented on src/schemes/solid/discrete_element_method/system.jl
> +                   typeof(mass),
```suggestion
        return new{NDIMS, ELTYPE, typeof(initial_condition), typeof(mass),
```

2024-05-29 08:05 UTC, efaulhaber commented on src/schemes/boundary/system.jl
> +                   typeof(initial_condition),
I like having the type parameters on the left and the fields on the right.

2024-05-29 08:11 UTC, LasNikas approved these changes

2024-05-29 09:58 UTC, merged