Use new v0.3 release of PointNeighbors.jl
trixi-framework/TrixiParticles.jl pull request #550
Opened 2024-06-21 13:53 UTC by efaulhaber

2024-06-24 11:40 UTC, svchb submitted a review, later dismissed

2024-06-26 10:39 UTC, LasNikas commented on src/general/semidiscretization.jl
> +    Semidiscretization(systems...; neighborhood_search=GridNeighborhoodSearch{NDIMS}())
Please remove the keywords for the periodic box in the docs.

Or maybe, IMO, it is better to keep this keywords and create the nhs internally with the bounding box. Or only pass the `PeriodicBox`? Is there a reason why you changed it this way?

2024-06-26 11:13 UTC, svchb submitted a review, later dismissed

2024-06-26 14:13 UTC, svchb requested changes
Waiting for further breaking changes.

2024-06-26 16:03 UTC, efaulhaber commented
More breaking changes with https://github.com/trixi-framework/PointNeighbors.jl/pull/42.

2024-06-27 11:47 UTC, merged