Add plot recipe for initial condition
trixi-framework/TrixiParticles.jl pull request #585
Opened 2024-07-31 09:51 UTC by LasNikas

2024-07-31 10:35 UTC, efaulhaber requested changes

2024-07-31 10:35 UTC, efaulhaber commented on src/visualization/recipes_plots.jl
> +    end
All of this is duplicate code. Can you please make it a function?

2024-07-31 13:01 UTC, LasNikas commented on src/visualization/recipes_plots.jl
> +                               data...; zcolor=nothing, size=(600, 400), colorbar_title="")
yes

2024-07-31 13:09 UTC, LasNikas commented on src/visualization/recipes_plots.jl
> +                               data...; zcolor=nothing, size=(600, 400), colorbar_title="")
`plot(sol; size=(1200,300), zcolor=tank.fluid.pressure, colorbar_title="test")`
![image](https://github.com/user-attachments/assets/cec1e3be-e1fb-4203-82c8-ed316a923eb4)

2024-07-31 13:10 UTC, LasNikas commented on src/visualization/recipes_plots.jl
> +                               data...; zcolor=nothing, size=(600, 400), colorbar_title="")
`plot(tank.fluid; size=(1200,300), zcolor=tank.fluid.pressure, colorbar_title="test")`
![image](https://github.com/user-attachments/assets/8d334c17-382d-4482-9f23-3524467dfeb3)

2024-07-31 13:11 UTC, LasNikas commented on src/visualization/recipes_plots.jl
> +                               data...; zcolor=nothing, size=(600, 400), colorbar_title="")
even for other plot-kwargs
`plot(tank.fluid; size=(1200,300), zcolor=tank.fluid.pressure, colorbar_title="test",xaxis=false, yaxis=false)`
![image](https://github.com/user-attachments/assets/08dc6e3e-2ce5-4b94-9c9c-3f3a5075c327)

2024-08-01 08:25 UTC, efaulhaber approved these changes

2024-08-01 08:25 UTC, merged