Define boundary zone from STL-file
trixi-framework/TrixiParticles.jl pull request #597
Opened 2024-08-07 14:12 UTC by LasNikas

With this PR, we can pass arbitrary oriented planes (stl-file format) to the `InFlow` and `OutFlow` zones.
The reason for this is that for real-world problems one do not need to specify the plane points for the in- and outflow zones.

I basically added a function to calculate the oriented bounding box of an arbitrary oriented plane in space.

An example:
```julia
using TrixiParticles

particle_spacing = 0.01
density = 1000.0

open_boundary_layers = 8

filename_plane = "inflow_region_plane"
file_plane = joinpath(expanduser("~/"), "Data", "stl-files", "aorta", filename_plane * ".stl")

filename = "inflow_region"
file = joinpath(expanduser("~/"), "Data", "stl-files", "aorta", filename * ".stl")

geometry_plane = load_geometry(file_plane)

geometry = load_geometry(file)

algorithm = WindingNumberJacobson(; geometry, hierarchical_winding=true)
shape_sampled = ComplexShape(geometry; particle_spacing, density,
                             point_in_geometry_algorithm=algorithm)

flow_direction = TrixiParticles.normalize(sum(geometry_plane.face_normals) /
                                          TrixiParticles.nfaces(geometry_plane))

inflow = InFlow(; plane=geometry_plane, initial_condition=shape_sampled, flow_direction,
                open_boundary_layers, density, particle_spacing)

points = stack(inflow.spanning_set) .+ inflow.zone_origin
points[:, 1] .+= flow_direction*inflow.zone_width

trixi2vtk(points, flow_direction=fill(inflow.flow_direction, 3))

```
![Screenshot from 2024-08-07 16-00-51](https://github.com/user-attachments/assets/f49be239-a14e-49b3-b71b-559353c89c50)

2024-11-13 15:58 UTC, svchb approved these changes

2025-03-05 10:03 UTC, svchb requested changes
Please fix the tests

2025-07-29 18:12 UTC, LasNikas commented
/run-gpu-tests

2025-07-29 20:02 UTC, LasNikas commented
/run-gpu-tests

2025-08-16 10:26 UTC, efaulhaber requested changes
I don't understand the point of this, so I can't review the actual code.
Also, why are the particles not aligned here?
<img width="1260" height="1098" alt="grafik" src="https://github.com/user-attachments/assets/54b05a00-508c-4859-a44e-e6a2d94990d6" />
Why is the particle grid not parallel to the surface?

2025-08-16 10:26 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +The geometry must be planar (i.e., all vertices should lie approximately in the same plane).
I first read the docstring before looking in the code, and I'm confused.
1. Is "transition face" common terminology? If not, please use something more descriptive, because I can only imagine what a transition face is supposed to be.
2. First you say "The plane points are the corner points of an oriented bounding box of the given geometry", further down you say they are a "Tuple of three points defining the transition plane". Which is it?
3. What do you mean "the geometry must be planar"? I thought the point of this function would be to slice off a corner of the geometry and make it an inflow or so? If the geometry is just a plane, then what is the purpose of this function? Then you already have a plane, so what is this function doing?

2025-08-25 08:32 UTC, LasNikas commented on src/preprocessing/geometries/geometries.jl
> +The geometry must be planar (i.e., all vertices should lie approximately in the same plane).
The purpose of this function is to conveniently extract the transition plane information needed for the boundary zone. This includes the plane normal and the points that define the plane.
The function takes an arbitrary planar geometry (like an STL mesh of a plane with irregular boundaries) and extracts a clean rectangular representation suitable for boundary zone creation. Even though the input geometry is planar, it might have complex boundaries or be triangulated, so this function computes a simplified rectangular bounding box that captures the essential plane orientation and extent.

1. By "transition plane" I mean the surface of the boundary zone through which the fluid flows in or out. I'm not sure what else to call it?
2. Both, since we're dealing with the oriented bounding box of a planar geometry.
3. I need the points that define this rectangular plane for the transition plane, which are the corner points of the oriented bounding box. A planar geometry can have any arbitrary shape (see example).

2025-08-30 08:17 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +The geometry must be planar (i.e., all vertices should lie approximately in the same plane).
0. Now I understand what this is supposed to do. But then we need to find a better name. Maybe something more descriptive like `planar_geometry_to_face` or so?
1. How about a longer description then instead of finding a single confusing word? "interface between domain and boundary zone" maybe?
2. A box has 4 corners, a plane is infinite, therefore has no corners, and it is defined by three arbitrary points. Do you mean "tuple containing the first three corners of an oriented bounding box of the geometry"?

2025-08-30 08:18 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +The geometry must be planar (i.e., all vertices should lie approximately in the same plane).
Also, what about my question above?
> Also, why are the particles not aligned here?

2025-09-05 17:43 UTC, LasNikas commented on src/preprocessing/geometries/geometries.jl
> +The geometry must be planar (i.e., all vertices should lie approximately in the same plane).
Good points, I’ll update it accordingly.

> Also, why are the particles not aligned here?

This happens because I’m passing the sampled `InitialCondition`s from the inflow geometry directly.
If I instead create the `BoundaryZone` with `initial_condition=nothing` (default and plane will be extruded), the particles are aligned, as shown below.
Afterwards, overlapping particles can be removed using set operations together with the geometry.
However, I felt that this approach wasn’t particularly relevant in this context.

<img width="1039" height="618" alt="image" src="https://github.com/user-attachments/assets/f83b2382-554a-4ebf-bc40-db72590b9248" />

2025-09-15 10:42 UTC, svchb requested changes

2025-09-15 10:42 UTC, svchb commented on src/preprocessing/geometries/geometries.jl
> +    # Vectors spanning the plane
```suggestion
    # Vectors spanning the face
```

2025-09-15 10:42 UTC, svchb commented on src/schemes/boundary/open_boundary/boundary_zones.jl
>  opposite to `plane_normal` to create a box for the boundary zone.
```suggestion
opposite to `face_normal` to create a box for the boundary zone.
```

2025-09-15 10:42 UTC, svchb commented on examples/fluid/pipe_flow_2d.jl
> +inflow = BoundaryZone(; boundary_face=face_in, plane_normal=flow_direction,
```suggestion
inflow = BoundaryZone(; boundary_face=face_in, face_normal=flow_direction,
```

2025-09-15 10:42 UTC, svchb commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +- `plane_normal`: Vector defining the normal of the `boundary_face`. It always points inside the fluid domain.
```suggestion
- `face_normal`: Vector defining the normal of the `boundary_face`. It always points inside the fluid domain.
```

2025-09-15 10:42 UTC, svchb commented on test/preprocessing/geometries/geometries.jl
> +        plane, plane_normal = planar_geometry_to_face(plane_geometry)
```suggestion
        face, face_normal = planar_geometry_to_face(plane_geometry)
```

2025-09-15 10:42 UTC, svchb commented on test/preprocessing/geometries/geometries.jl
> +        plane_geometry = load_geometry(joinpath(file, "inflow_plane.stl"))
```suggestion
        inflow_geometry = load_geometry(joinpath(file, "inflow_bnd.stl"))
```

2025-09-15 13:11 UTC, svchb requested changes

2025-09-15 13:11 UTC, svchb commented on src/schemes/boundary/open_boundary/boundary_zones.jl
>      reference_values  :: R
FN instead of PN

2025-09-19 07:08 UTC, efaulhaber requested changes

2025-09-19 07:08 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +# to avoid circular dependencies with `TriangleMesh`
1. There is no `boundary_zone.jl`.
2. This function is not used anywhere.

2025-09-19 07:08 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +    The returned plane normal is computed by averaging all face normals, so consistent orientation is required.
How does one do that? Say I'm a user, and I have an STL file. Now I load it with `load_geometry`. What now? Why is it my responsibility to do anything with normals?

2025-09-19 07:08 UTC, efaulhaber commented on src/preprocessing/geometries/geometries.jl
> +    end
1. This is a weird check. You take the cross product of the edges and then make all coordinates positive and compare with the normal with all coordinates positive?
2. The error is also weird. What do you mean "might"? Either you confirmed it's not planar and throw an error, or you're not sure and show a warning.

```suggestion
    if abs(dot(edge1, face_normal)) > 1e-2 || abs(dot(edge2, face_normal)) > 1e-2
        throw(ArgumentError("geometry is not planar"))
    end
```

2025-09-19 07:08 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +    BoundaryZone(; boundary_face, face_normal, density, particle_spacing,
Breaking change requires a mention in NEWS.md.

2025-09-19 07:21 UTC, LasNikas commented on src/preprocessing/geometries/geometries.jl
> +    The returned plane normal is computed by averaging all face normals, so consistent orientation is required.
When it comes to complex simulations, users will typically preprocess or create the geometry using a CAD programme or Blender. And than it is important to ensure that the normals consistently point inside the fluid domain. This is a common pre-processing chain...

2025-09-19 07:22 UTC, LasNikas commented on src/preprocessing/geometries/geometries.jl
> +    The returned plane normal is computed by averaging all face normals, so consistent orientation is required.
It's one click in blender to swap normals

2025-09-19 07:55 UTC, efaulhaber commented on NEWS.md
> +- Rename keyword arguments `plane` and `plane_normal` for `BoundaryZone` to `boundary_face` and `face_normal` (#597).
I tried to sort these by relevance. Can you move this below the "API for `OpenBoundarySystem` changed"?

2025-09-19 08:36 UTC, merged