Remove soundspeed from openboundary system
trixi-framework/TrixiParticles.jl pull request #605
Opened 2024-08-20 15:31 UTC by svchb

Saving sound speed in the openboundary system makes no sense especially in the context of multiple fluids that can be at the openboundary.
As such remove sound speed and reuse the information from the fluid system(s).

Extracted from #604

2024-09-05 15:00 UTC, efaulhaber approved these changes
Looks reasonable to me, but I would like to let @LasNikas have a look.

2024-09-19 10:33 UTC, LasNikas requested changes
Good point thanks. 
IMO, we then don't need a wrapper for the `OpenBoundarySPHSystem`

2024-09-19 10:33 UTC, LasNikas commented on src/schemes/boundary/open_boundary/method_of_characteristics.jl
> +    sound_speed = system_sound_speed(system)
```suggestion
    sound_speed = system_sound_speed(system.fluid_system)
```

2024-09-19 10:33 UTC, LasNikas commented on src/schemes/boundary/open_boundary/method_of_characteristics.jl
> +    sound_speed = system_sound_speed(system)
```suggestion
    sound_speed = system_sound_speed(system.fluid_system)
```

2024-09-19 10:33 UTC, LasNikas commented on src/schemes/boundary/open_boundary/system.jl
> +@inline system_sound_speed(system::OpenBoundarySPHSystem) = system_sound_speed(system.fluid_system)
```suggestion
```

2024-09-26 07:18 UTC, merged