Revise boundary zones and allow bidirectional flow
trixi-framework/TrixiParticles.jl pull request #623
Opened 2024-09-30 13:25 UTC by LasNikas

2024-10-03 13:20 UTC, svchb requested changes

2024-10-03 13:20 UTC, svchb commented on src/general/semidiscretization.jl
> +    end
So the indention for this model is just pipe and channel flows?
This should be clarified in the documentation.

2025-02-10 12:18 UTC, efaulhaber requested changes

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +    end
Else?

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +        # First vector of `spanning_vectors` is normal to the boundary plane.
```suggestion
        # First vector of `spanning_vectors` is normal to the boundary plane
```

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +        # Flip the normal vector to point in the opposite direction of `flow_direction`
```suggestion
        # Flip the normal vector to point in the opposite direction of `flow_direction`.
```

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +        # First vector of `spanning_vectors` is normal to the boundary plane.
```suggestion
        # First vector of `spanning_vectors` is normal to the boundary plane
```

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +        # Flip the normal vector to point in `flow_direction`
```suggestion
        # Flip the normal vector to point in `flow_direction`.
```

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/system.jl
> +    particle_position = current_coords(u, system, particle) - boundary_zone.zone_origin
```suggestion
    relative_position = current_coords(u, system, particle) - boundary_zone.zone_origin
```
Maybe a bit clearer?

2025-02-10 12:18 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/system.jl
> +    # `plane_normal` is always pointing in the fluid domain.
```suggestion
    # `plane_normal` is always pointing into the fluid domain.
```

2025-02-20 11:14 UTC, efaulhaber commented on src/schemes/boundary/open_boundary/boundary_zones.jl
> +struct OutFlow end
I think types are better and more consistent with the rest of the TrixiParticles API.

2025-02-21 11:38 UTC, svchb requested changes

2025-02-21 11:38 UTC, svchb commented on src/schemes/boundary/open_boundary/boundary_zones.jl
>  - `open_boundary_layers`: Number of particle layers in upstream direction.
```suggestion
- `open_boundary_layers`: Number of particle layers in the direction opposite to `plane_normal`.
```

2025-03-05 10:09 UTC, svchb approved these changes

2025-03-05 14:09 UTC, efaulhaber approved these changes

2025-03-06 10:25 UTC, merged