dd set operations for geometries
trixi-framework/TrixiParticles.jl pull request #636
Opened 2024-10-23 12:15 UTC by LasNikas

2024-10-24 07:15 UTC, svchb requested changes

2024-10-24 07:15 UTC, svchb commented on src/general/initial_condition.jl
> +        throw(ArgumentError("all passed geometries must have the same dimensionality as the initial condition"))
```suggestion
        throw(ArgumentError("All passed geometries must have the same dimensionality as the initial condition."))
```

2024-10-24 07:15 UTC, svchb commented on src/general/initial_condition.jl
> +    return setdiff(result, Base.tail(geometries)...)
Aren't all of the particles already removed that are in the geometry?

2024-10-24 07:15 UTC, svchb commented on src/general/initial_condition.jl
> +        throw(ArgumentError("all passed geometries must have the same dimensionality as the initial condition"))
```suggestion
        throw(ArgumentError("All passed geometries must have the same dimensionality as the initial condition."))
```

2024-10-24 07:24 UTC, svchb commented on src/general/initial_condition.jl
> +    return setdiff(result, Base.tail(geometries)...)
ah I see!

2024-10-24 07:35 UTC, LasNikas commented on src/general/initial_condition.jl
> +        throw(ArgumentError("all passed geometries must have the same dimensionality as the initial condition"))
see #133:

> In Julia, sentence fragments starting with lowercase and no punctuation seem to be preferred

2024-10-24 07:35 UTC, LasNikas commented on src/general/initial_condition.jl
> +        throw(ArgumentError("all passed geometries must have the same dimensionality as the initial condition"))
see #133:

> In Julia, sentence fragments starting with lowercase and no punctuation seem to be preferred

2024-10-24 08:22 UTC, svchb commented on src/general/initial_condition.jl
> +        throw(ArgumentError("all passed geometries must have the same dimensionality as the initial condition"))
I always forget that.

2025-01-07 16:14 UTC, efaulhaber submitted a review, later dismissed

2025-01-08 10:46 UTC, svchb requested changes

2025-01-08 10:46 UTC, svchb commented on src/setups/complex_shape.jl
> +function Base.setdiff(initial_condition::InitialCondition,
Please add documentation

2025-01-08 10:46 UTC, svchb commented on src/setups/complex_shape.jl
> +function Base.intersect(initial_condition::InitialCondition,
Please add documentation

2025-01-08 14:38 UTC, svchb approved these changes

2025-01-08 15:27 UTC, merged