Improve Test Coverage
trixi-framework/TrixiParticles.jl pull request #674
Opened 2024-11-21 08:54 UTC by svchb

2024-12-02 08:11 UTC, efaulhaber requested changes

2024-12-02 08:11 UTC, efaulhaber commented on test/schemes/boundary/dummy_particles/dummy_particles.jl
> +                # Neighborhood search
```suggestion
```
Redundant comment (clear from the variable name).

2024-12-02 08:11 UTC, efaulhaber commented on test/schemes/boundary/dummy_particles/dummy_particles.jl
> +                scales = [1.0, 0.5, 0.7, 1.8, 67.5]
```suggestion
                scale_factors = [1.0, 0.5, 0.7, 1.8, 67.5]
```

2024-12-02 11:13 UTC, efaulhaber approved these changes

2024-12-02 11:13 UTC, efaulhaber commented
@LasNikas do you want to take a look as well before this is merged?

2024-12-10 17:47 UTC, svchb commented
@LasNikas Reminder! This waits for over a week now.

2024-12-11 05:39 UTC, LasNikas approved these changes

2024-12-11 05:39 UTC, merged