Make GPUs actually usable
trixi-framework/TrixiParticles.jl pull request #689
Opened 2024-12-23 19:12 UTC by efaulhaber

Based on https://github.com/trixi-framework/PointNeighbors.jl/pull/90 and https://github.com/trixi-framework/TrixiBase.jl/pull/35.

This PR contains the following changes:
- TLSPH (and therefore FSI examples) now works on GPUs.
- TLSPH now works with `Float32` (and therefore on Apple GPUs that don't support double precision).
- Plotting now works on the GPU.
- I added a new macro `trixi_include_changeprecision(Float32, example_file)` to conveniently change all `Float64` literals in an example file to `Float32`, which is enough to make the whole simulation run with single precision (that's how we designed the code).

2025-02-18 10:02 UTC, svchb requested changes
A few selected examples should be executed for GPU compatibility so that more of the features are checked.

2025-02-20 09:50 UTC, efaulhaber commented on docs/src/gpu.md
>  as cell list for the [`GridNeighborhoodSearch`](@ref).
Why would you want to remove "the"?

2025-02-20 09:52 UTC, efaulhaber commented on docs/src/gpu.md
> +This requires the assignments `neighborhood_search = ...` and `data_type = ...` in the
We don't just have to set this somehow. We explicitly need this assignment in the file. How about
```suggestion
This requires the assignments `neighborhood_search = ...` and `data_type = ...` to be present in the
```

2025-02-20 11:01 UTC, efaulhaber commented
> A few selected examples should be executed for GPU compatibility so that more of the features are checked.

We would need a self-hosted runner with a GPU to test any of this.

2025-02-21 01:51 UTC, svchb commented on docs/src/gpu.md
>  as cell list for the [`GridNeighborhoodSearch`](@ref).
Just stylistic choice I guess.

2025-02-21 01:52 UTC, svchb commented on docs/src/gpu.md
> +This requires the assignments `neighborhood_search = ...` and `data_type = ...` in the
also fine

2025-02-24 16:20 UTC, efaulhaber commented
> We would need a self-hosted runner with a GPU to test any of this.

See #723 (which is based on this PR).

2025-03-03 16:58 UTC, LasNikas reviewed
Thanks a lot. It would be nice to have the precision and the hardware information in the summary box of the environment information. Is this possible?

2025-03-03 16:58 UTC, LasNikas commented on src/schemes/solid/total_lagrangian_sph/system.jl
> -end
That means FSI isn't supported for `BoundaryModelDummyParticles{ContinuityDensity}`?
Is this somewhere mentioned?
Then you can also remove `write_v0!(v0, boundary_model, system)` in line 349 and the corresponding method in line 354-356

2025-03-03 16:58 UTC, LasNikas commented on src/visualization/recipes_plots.jl
> +                               particle_spacings=TrixiParticles.particle_spacings(semi),
```suggestion
                               particle_spacings=particle_spacings(semi),
```
Why do you need this? It's defined in the module scope?

2025-03-03 17:15 UTC, LasNikas commented on docs/src/gpu.md
> +trixi_include(joinpath(examples_dir(), "fluid", "dam_break_2d_gpu.jl"), data_type=MtlArray())
```suggestion
trixi_include(joinpath(examples_dir(), "fluid", "dam_break_2d_gpu.jl"), data_type=MtlArray)
```
?
Also, since only `Float32` is supported:
```julia
trixi_include_changeprecision(Float32,
                                     joinpath(examples_dir(), "fluid", "dam_break_2d_gpu.jl"),
                                     data_type=MtlArray)
```

2025-03-04 09:40 UTC, efaulhaber commented on src/schemes/solid/total_lagrangian_sph/system.jl
> -end
https://github.com/trixi-framework/TrixiParticles.jl/issues/370

2025-03-04 09:56 UTC, efaulhaber commented on src/schemes/solid/total_lagrangian_sph/system.jl
> -end
No wait, now I'm confused. I don't know why I removed this function.

2025-03-04 17:30 UTC, LasNikas approved these changes

2025-03-05 08:15 UTC, svchb approved these changes

2025-03-05 08:15 UTC, merged